#pragma once

// macros to allow for anchor to be read as bitwise flags
#include <SDL3/SDL_rect.h>
#define ALIGN_VERTICAL_TOP 0b01
#define ALIGN_VERTICAL_BOTTOM 0b10
#define ALIGN_VERTICAL_CENTER 0b11
#define ALIGN_HORIZONTAL_LEFT 0b0100
#define ALIGN_HORIZONTAL_RIGHT 0b1000
#define ALIGN_HORIZONTAL_CENTER 0b1100

#define ALIGN_VERTICAL_MASK 0b11
#define ALIGN_HORIZONTAL_MASK 0b1100

namespace common {

enum Anchor {
	TOP_LEFT = ALIGN_VERTICAL_TOP | ALIGN_HORIZONTAL_LEFT,
	TOP = ALIGN_VERTICAL_TOP | ALIGN_HORIZONTAL_CENTER,
	TOP_RIGHT = ALIGN_VERTICAL_TOP | ALIGN_HORIZONTAL_RIGHT,
	LEFT = ALIGN_VERTICAL_CENTER | ALIGN_HORIZONTAL_LEFT,
	CENTER = ALIGN_VERTICAL_CENTER | ALIGN_HORIZONTAL_CENTER,
	RIGHT = ALIGN_VERTICAL_CENTER | ALIGN_HORIZONTAL_RIGHT,
	BOTTOM_LEFT = ALIGN_VERTICAL_BOTTOM | ALIGN_HORIZONTAL_LEFT,
	BOTTOM = ALIGN_VERTICAL_BOTTOM | ALIGN_HORIZONTAL_CENTER,
	BOTTOM_RIGHT = ALIGN_VERTICAL_BOTTOM | ALIGN_HORIZONTAL_RIGHT
};

struct position {
	Anchor anchor;
	int xOffset;
	int yOffset;
	int width;
	int height;
};

struct bounds {
	float x1, y1, x2, y2;
};

} // namespace common